[package]
name = "hnx-kernel"
version = "0.0.1"
edition = "2021"
authors = ["HNX Developer"]

[lib]
crate-type = ["staticlib"]

[dependencies]
hnx-abi = { path = "../abi-bindings" }
log = "0.4"
spin = "0.9"

[features]
default = []
qemu_test = []