# rust-toolchain.toml
[toolchain]
channel = "nightly"
components = ["rust-src", "llvm-tools-preview", "rustfmt", "clippy"]
targets = ["aarch64-unknown-none", "x86_64-unknown-none"]
profile = "minimal"