[package]
name = "vfs-service"
version = "0.1.0"
edition = "2021"

[dependencies]
spin = "0.9"
shared = { path = "../../../shared" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "z"
lto = true