[package]
name = "loader-service"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../../../shared" }
libc = { path = "../../libc" }
hnxlib = { path = "../../hnxlib" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
